AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'Gemfile.lock'
    - pkg/**/*

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Dir:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Performance/RegexpMatch:
  Enabled: false
