language: java
sudo: false
before_script:
  - export MAVEN_SKIP_RC=true
env:
  - GOAL=test
  # the install_ruby_maven_when_needed can not resolve ruby-maven on travis
  # gemspecs was and is very fragile - probably remove it completely as it is doing too much in one go
  - GOAL='verify -Dmaven.test.skip -Dinvoker.test=*,!install*,!gemspecs'
jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8
install: ./mvnw initialize
script: ./mvnw $GOAL
