name: jar-dependencies

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: [jruby-9.4, jruby-10.0, jruby-head]

    steps:
      - uses: actions/checkout@v6
      - name: Set up JRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Download Mima jars
        run: bundle exec rake download_jars
      - name: Run tests
        run: bundle exec rake specs
      - name: Run RuboCop
        if: matrix.ruby-version == 'jruby-10.0' # Only run RuboCop on modern JRuby; target older jrubies via .rubocop.yml
        run: bundle exec rubocop lib
